version: "3"

services:
  homarr:
    image: "ghcr.io/ajnart/homarr:latest"
    hostname: www
    environment:
      - TZ='Asia/Tokyo'
      - PORT=80
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
    networks:
      external-network: 
        ipv4_address: 192.168.100.224
    restart: always

networks:
    external-network:
      external: true
