version: "3"

services:
  bash:
    image: "rtsp/net-tools:latest"
    environment:
      - TZ='Asia/Tokyo'
    user: 1000:1000
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro